import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useAuth } from '../context/AuthContext';
import {
  Brain, MessageSquare, FileQuestion, Youtube, TrendingUp,
  ArrowRight, Check, Menu, X, GraduationCap, Building2, Users,
  ShieldCheck, Sparkles, LineChart,
} from 'lucide-react';

const TOOLS = [
  {
    name: 'EduPredict',
    tagline: 'Academic early-warning system',
    icon: TrendingUp,
    color: '#FF5722',
    description:
      'A temporal LightGBM model reads engagement, assessment and registration signals to flag students who are drifting toward failure — while there is still time to intervene.',
    points: [
      'Risk level, probability and confidence per student',
      'Five course checkpoints: day 0, 30, 60, 90 and 150',
      'Data-completeness check flags unreliable predictions',
    ],
    stack: ['LightGBM', 'OULAD', 'FastAPI'],
  },
  {
    name: 'LectureScribe',
    tagline: 'Automatic lecture transcription',
    icon: Youtube,
    color: '#76ABAE',
    description:
      'Turns a recorded lecture link into a clean, structured transcript. Built for the mixed Arabic–English speech that engineering lectures actually use.',
    points: [
      'Faster-Whisper speech-to-text with GPU acceleration',
      'An LLM pass removes fillers and repairs broken sentences',
      'Preserves detail and order — it formats, it does not summarise',
    ],
    stack: ['Faster-Whisper', 'CTranslate2', 'FFmpeg'],
  },
  {
    name: 'Academic Chatbot',
    tagline: 'Ask the university anything',
    icon: MessageSquare,
    color: '#FF5722',
    description:
      'A retrieval-augmented assistant over institutional knowledge — programs, fees, scholarships, admission and student services — answering natural-language questions in Arabic.',
    points: [
      'Semantic search with Jina Embeddings v3',
      'Answers generated by Groq LLaMA 3.1',
      'Knowledge base extended at runtime, no redeploy',
    ],
    stack: ['RAG', 'MongoDB Atlas', 'Groq'],
  },
  {
    name: 'QuizForge',
    tagline: 'Automated assessment generation',
    icon: FileQuestion,
    color: '#76ABAE',
    description:
      'Upload lecture notes, a PDF or a scanned page and get exam-ready questions back — multiple choice, true/false and essay — in seconds instead of an evening.',
    points: [
      'Tesseract OCR handles scanned and handwritten material',
      'Magic-byte validation blocks spoofed file types',
      'Copy, download and revisit previously generated sets',
    ],
    stack: ['Tesseract OCR', 'Groq', 'React'],
  },
];

const AUDIENCE = [
  {
    icon: GraduationCap,
    title: 'Students',
    body: 'Review lectures as readable text, generate practice questions from your own notes, ask academic questions in plain language, and see your own risk indicators privately.',
  },
  {
    icon: Users,
    title: 'Instructors',
    body: 'Turn course material into quizzes and question banks without the repetitive manual work, and archive lecture content as searchable documents.',
  },
  {
    icon: LineChart,
    title: 'Academic advisors',
    body: 'A monitoring dashboard with filtered at-risk lists, trends across course checkpoints and per-student risk profiles — early enough to act on.',
  },
];

const METRICS = [
  { value: '4', label: 'AI tools, one platform' },
  { value: '91.8%', label: 'EduPredict accuracy' },
  { value: '92.0%', label: 'F1-score on holdout' },
  { value: '5', label: 'Prediction checkpoints' },
];

const STEPS = [
  {
    title: 'Sign in',
    body: 'Create a demo student profile, or sign in with the account your institution issued you.',
  },
  {
    title: 'Pick a tool',
    body: 'Everything lives behind one dashboard — prediction, transcription, chatbot and question generation.',
  },
  {
    title: 'Act on the result',
    body: 'Transcripts to revise from, questions to practise with, and risk signals advisors can follow up on.',
  },
];

const NAV_LINKS = [
  { href: '#tools', label: 'Tools' },
  { href: '#audience', label: 'Who it is for' },
  { href: '#how', label: 'How it works' },
  { href: '#about', label: 'About' },
];

const TEAM = [
  'Abdallah Saeed Fsafis',
  'Abdullah Mohammed Shehdada',
  'Ahmed Noaman Kalloub',
  'Basem Hamdi Daqarem',
  'Nizar Yousef Alqerem',
];

const INSTITUTION_TAGS = [
  'Institutional sign-in',
  'Records read from the university SIS',
  'Role-based access control',
  'Student data stays private to the student',
];

const Section = ({ id, children, className = '' }) => (
  <section id={id} className={`mx-auto w-full max-w-6xl px-5 sm:px-8 ${className}`}>
    {children}
  </section>
);

const Reveal = ({ children, delay = 0, className = '' }) => (
  <motion.div
    initial={{ opacity: 0, y: 20 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true, margin: '-80px' }}
    transition={{ duration: 0.5, delay, ease: [0.22, 1, 0.36, 1] }}
    className={className}
  >
    {children}
  </motion.div>
);

const CLIPS = ['/edufusion-preview-1.mp4', '/edufusion-preview-2.mp4'];
const CROSSFADE_MS = 700;

/**
 * Ambient concept film: the clips play back to back on an endless loop, with the
 * next one fading in over the tail of the current one so the seam is not visible.
 * The files carry no audio track at all, so there is nothing to mute and no
 * controls are rendered — it is decorative, not a player.
 */
const PreviewFilm = () => {
  const videoRefs = useRef([]);
  const [active, setActive] = useState(0);
  const activeRef = useRef(0);
  const switchingRef = useRef(false);

  const playClip = (index) => {
    const video = videoRefs.current[index];
    if (!video) return;
    video.muted = true;
    video.currentTime = 0;
    video.play?.()?.catch(() => {});
  };

  useEffect(() => {
    playClip(0);
  }, []);

  // Start the next clip while the current one is still on screen, then let the
  // CSS opacity transition carry the hand-off.
  const advanceFrom = (index) => {
    if (switchingRef.current || activeRef.current !== index) return;
    switchingRef.current = true;

    const next = (index + 1) % CLIPS.length;
    playClip(next);
    activeRef.current = next;
    setActive(next);

    window.setTimeout(() => {
      const finished = videoRefs.current[index];
      if (finished) {
        finished.pause();
        finished.currentTime = 0;
      }
      switchingRef.current = false;
    }, CROSSFADE_MS);
  };

  const handleTimeUpdate = (index) => {
    const video = videoRefs.current[index];
    if (!video || !Number.isFinite(video.duration)) return;
    if (video.duration - video.currentTime <= CROSSFADE_MS / 1000) advanceFrom(index);
  };

  return (
    <div className="relative overflow-hidden rounded-3xl border border-border bg-light-accent shadow-2xl shadow-light-accent/15">
      {/* Fixed ratio box so the section does not jump while the first clip loads. */}
      <div className="relative w-full" style={{ aspectRatio: '16 / 9' }}>
        {CLIPS.map((src, index) => (
          <video
            key={src}
            ref={(el) => { videoRefs.current[index] = el; }}
            className="absolute inset-0 h-full w-full object-cover transition-opacity ease-linear"
            style={{ opacity: active === index ? 1 : 0, transitionDuration: `${CROSSFADE_MS}ms` }}
            src={src}
            poster={index === 0 ? '/edufusion-preview-poster.jpg' : undefined}
            muted
            playsInline
            preload="auto"
            disablePictureInPicture
            aria-hidden="true"
            tabIndex={-1}
            onTimeUpdate={() => handleTimeUpdate(index)}
            onEnded={() => advanceFrom(index)}
          />
        ))}
      </div>
    </div>
  );
};

export default function Landing() {
  const { isAuthenticated, loading } = useAuth();
  const navigate = useNavigate();
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 8);
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  const primaryCta = isAuthenticated
    ? { to: '/dashboard', label: 'Open dashboard' }
    : { to: '/register', label: 'Create an account' };

  return (
    <div className="min-h-screen bg-primary text-light-accent">
      {/* ---------- Nav ---------- */}
      <header
        className={`sticky top-0 z-50 transition-colors duration-300 ${
          scrolled ? 'bg-primary/85 backdrop-blur-xl border-b border-border' : 'border-b border-transparent'
        }`}
      >
        <div className="mx-auto flex h-16 w-full max-w-6xl items-center gap-4 px-5 sm:px-8">
          <Link to="/" className="flex items-center gap-2.5">
            <span className="flex h-9 w-9 items-center justify-center rounded-xl" style={{ background: '#76ABAE' }}>
              <Brain className="h-5 w-5 text-white" />
            </span>
            <span className="font-display text-base font-bold tracking-tight">EduFusion AI</span>
          </Link>

          <nav className="ml-auto hidden items-center gap-1 md:flex">
            {NAV_LINKS.map((link) => (
              <a
                key={link.href}
                href={link.href}
                className="rounded-lg px-3 py-2 text-sm text-light-accent/65 transition-colors hover:bg-secondary/10 hover:text-light-accent"
              >
                {link.label}
              </a>
            ))}
          </nav>

          <div className="ml-auto flex items-center gap-2 md:ml-4">
            {!loading && !isAuthenticated && (
              <Link
                to="/login"
                className="hidden rounded-xl px-3.5 py-2 text-sm font-medium text-light-accent/75 transition-colors hover:bg-secondary/10 hover:text-light-accent sm:inline-flex"
              >
                Sign in
              </Link>
            )}
            <Link
              to={primaryCta.to}
              className="inline-flex items-center gap-1.5 rounded-xl px-4 py-2 text-sm font-semibold text-white shadow-sm transition-transform hover:-translate-y-0.5"
              style={{ background: '#76ABAE' }}
            >
              {primaryCta.label}
              <ArrowRight className="h-3.5 w-3.5" />
            </Link>
            <button
              type="button"
              onClick={() => setMenuOpen((prev) => !prev)}
              className="inline-flex h-9 w-9 items-center justify-center rounded-lg text-light-accent/70 md:hidden"
              aria-label={menuOpen ? 'Close menu' : 'Open menu'}
            >
              {menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
            </button>
          </div>
        </div>

        {menuOpen && (
          <div className="border-t border-border bg-surface px-5 py-3 md:hidden">
            {NAV_LINKS.map((link) => (
              <a
                key={link.href}
                href={link.href}
                onClick={() => setMenuOpen(false)}
                className="block rounded-lg px-3 py-2.5 text-sm text-light-accent/75 hover:bg-secondary/10"
              >
                {link.label}
              </a>
            ))}
            {!isAuthenticated && (
              <Link
                to="/login"
                onClick={() => setMenuOpen(false)}
                className="block rounded-lg px-3 py-2.5 text-sm font-medium text-light-accent"
              >
                Sign in
              </Link>
            )}
          </div>
        )}
      </header>

      {/* ---------- Hero ---------- */}
      <div className="relative overflow-hidden">
        <div className="grid-pattern pointer-events-none absolute inset-0 opacity-60" aria-hidden="true" />
        <div
          className="pointer-events-none absolute -top-40 left-1/2 h-[420px] w-[720px] -translate-x-1/2 rounded-full blur-3xl"
          style={{ background: 'radial-gradient(circle, rgba(118,171,174,0.28), transparent 65%)' }}
          aria-hidden="true"
        />
        <Section className="relative pb-16 pt-16 sm:pt-24">
          <Reveal className="mx-auto max-w-3xl text-center">
            <span className="inline-flex items-center gap-2 rounded-full border border-border bg-surface px-3.5 py-1.5 text-xs font-mono uppercase tracking-widest text-light-accent/60">
              <Sparkles className="h-3.5 w-3.5 text-accent" />
              Islamic University of Gaza · Graduation Project
            </span>

            <h1 className="mt-6 font-display text-4xl font-bold leading-[1.1] tracking-tight sm:text-6xl">
              Four AI tools for digital education,
              <span className="text-gradient"> in one platform</span>
            </h1>

            <p className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-light-accent/65 sm:text-lg">
              EduFusion AI brings academic risk prediction, lecture transcription, a university
              chatbot and automatic question generation together behind a single dashboard — so
              students, instructors and advisors stop switching between disconnected tools.
            </p>

            <div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row">
              <Link
                to={primaryCta.to}
                className="inline-flex w-full items-center justify-center gap-2 rounded-xl px-6 py-3.5 text-sm font-semibold text-white shadow-lg shadow-secondary/25 transition-transform hover:-translate-y-0.5 sm:w-auto"
                style={{ background: '#76ABAE' }}
              >
                {primaryCta.label}
                <ArrowRight className="h-4 w-4" />
              </Link>
              <a
                href="#tools"
                className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-border bg-surface px-6 py-3.5 text-sm font-semibold text-light-accent transition-colors hover:border-secondary/50 sm:w-auto"
              >
                Explore the tools
              </a>
            </div>

            <p className="mt-4 text-xs text-light-accent/45">
              Free demo account · No email required · Takes under a minute
            </p>
          </Reveal>

          <Reveal delay={0.15} className="mt-16">
            <div className="glass glow-border grid grid-cols-2 overflow-hidden rounded-2xl md:grid-cols-4">
              {METRICS.map((metric) => (
                <div key={metric.label} className="px-5 py-6 text-center">
                  <p className="font-display text-3xl font-bold text-light-accent">{metric.value}</p>
                  <p className="mt-1 text-xs text-light-accent/50">{metric.label}</p>
                </div>
              ))}
            </div>
          </Reveal>
        </Section>
      </div>

      {/* ---------- Concept film ---------- */}
      <Section id="preview" className="scroll-mt-20 pb-4 pt-4">
        <Reveal>
          <PreviewFilm />
          <p className="mt-4 text-center text-xs text-light-accent/45">
            A short concept film of the platform. The working product lives behind the dashboard —{' '}
            <Link to="/register" className="text-secondary hover:underline">
              create an account
            </Link>{' '}
            to try it.
          </p>
        </Reveal>
      </Section>

      {/* ---------- Problem framing ---------- */}
      <Section className="py-16">
        <Reveal className="mx-auto max-w-3xl text-center">
          <h2 className="font-display text-2xl font-bold sm:text-3xl">
            Educational AI is powerful — and scattered
          </h2>
          <p className="mt-4 text-light-accent/65">
            University information sits in PDFs nobody searches. Lecture recordings go unreviewed,
            because scrubbing a two-hour video for one definition is not studying. Quizzes are
            written by hand. And students in trouble are usually identified after the final grade,
            when nothing can be done about it. EduFusion AI takes on all four in one place.
          </p>
        </Reveal>
      </Section>

      {/* ---------- Tools ---------- */}
      <Section id="tools" className="scroll-mt-20 py-8 sm:py-12">
        <Reveal className="mb-10 max-w-2xl">
          <p className="font-mono text-xs uppercase tracking-widest text-accent">The platform</p>
          <h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">Four tools, one login</h2>
          <p className="mt-3 text-light-accent/60">
            Each tool was built and evaluated independently, then integrated into a shared interface
            with a single account and role-based access.
          </p>
        </Reveal>

        <div className="grid gap-5 md:grid-cols-2">
          {TOOLS.map((tool, index) => (
            <Reveal key={tool.name} delay={index * 0.06}>
              <article className="glass glow-border h-full rounded-2xl p-6 transition-colors hover:border-secondary/45 sm:p-7">
                <div className="flex items-start gap-4">
                  <span
                    className="flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-xl"
                    style={{ background: `${tool.color}1f` }}
                  >
                    <tool.icon className="h-5 w-5" style={{ color: tool.color }} />
                  </span>
                  <div className="min-w-0">
                    <h3 className="font-display text-lg font-bold">{tool.name}</h3>
                    <p className="text-xs font-mono uppercase tracking-wider text-light-accent/45">
                      {tool.tagline}
                    </p>
                  </div>
                </div>

                <p className="mt-4 text-sm leading-relaxed text-light-accent/70">{tool.description}</p>

                <ul className="mt-5 space-y-2.5">
                  {tool.points.map((point) => (
                    <li key={point} className="flex items-start gap-2.5 text-sm text-light-accent/65">
                      <Check className="mt-0.5 h-4 w-4 flex-shrink-0" style={{ color: tool.color }} />
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>

                <div className="mt-5 flex flex-wrap gap-1.5 border-t border-border/70 pt-5">
                  {tool.stack.map((tech) => (
                    <span
                      key={tech}
                      className="rounded-md bg-surface-2 px-2 py-1 font-mono text-[11px] text-light-accent/55"
                    >
                      {tech}
                    </span>
                  ))}
                </div>
              </article>
            </Reveal>
          ))}
        </div>
      </Section>

      {/* ---------- Audience ---------- */}
      <Section id="audience" className="scroll-mt-20 py-16">
        <Reveal className="mb-10 max-w-2xl">
          <p className="font-mono text-xs uppercase tracking-widest text-accent">Who it is for</p>
          <h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">
            Three roles, one shared source of truth
          </h2>
        </Reveal>

        <div className="grid gap-5 md:grid-cols-3">
          {AUDIENCE.map((item, index) => (
            <Reveal key={item.title} delay={index * 0.08}>
              <div className="h-full rounded-2xl border border-border bg-surface p-6">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary/15">
                  <item.icon className="h-5 w-5 text-secondary" />
                </span>
                <h3 className="mt-4 font-display text-lg font-bold">{item.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-light-accent/65">{item.body}</p>
              </div>
            </Reveal>
          ))}
        </div>
      </Section>

      {/* ---------- How it works ---------- */}
      <Section id="how" className="scroll-mt-20 py-8 sm:py-12">
        <div className="glass glow-border overflow-hidden rounded-3xl p-8 sm:p-12">
          <Reveal className="max-w-2xl">
            <p className="font-mono text-xs uppercase tracking-widest text-accent">How it works</p>
            <h2 className="mt-3 font-display text-3xl font-bold">Three steps to your first result</h2>
          </Reveal>

          <div className="mt-10 grid gap-8 md:grid-cols-3">
            {STEPS.map((step, index) => (
              <Reveal key={step.title} delay={index * 0.08}>
                <div className="relative">
                  <span className="font-display text-4xl font-bold text-secondary/25">0{index + 1}</span>
                  <h3 className="mt-2 font-display text-lg font-bold">{step.title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-light-accent/65">{step.body}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </Section>

      {/* ---------- Institutional note ---------- */}
      <Section className="py-16">
        <Reveal>
          <div className="rounded-2xl border border-border bg-surface p-7 sm:p-9">
            <div className="flex flex-col gap-6 sm:flex-row sm:items-start">
              <span className="flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-xl bg-accent/10">
                <Building2 className="h-5 w-5 text-accent" />
              </span>
              <div className="min-w-0">
                <h3 className="font-display text-xl font-bold">Built to plug into an institution</h3>
                <p className="mt-3 text-sm leading-relaxed text-light-accent/65">
                  What you can try here is a demo: you enter your own academic details so the
                  prediction model has something to work with. In a real deployment none of that is
                  typed by hand — accounts come from the university directory, and enrolment,
                  assessment and activity records are read from the institution&apos;s own systems.
                  Students would simply sign in with the university account they already have.
                </p>
                <div className="mt-5 flex flex-wrap gap-2">
                  {INSTITUTION_TAGS.map((tag) => (
                    <span
                      key={tag}
                      className="inline-flex items-center gap-1.5 rounded-lg bg-surface-2 px-2.5 py-1.5 text-xs text-light-accent/60"
                    >
                      <ShieldCheck className="h-3.5 w-3.5 text-secondary" />
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </Reveal>
      </Section>

      {/* ---------- CTA ---------- */}
      <Section className="pb-16">
        <Reveal>
          <div
            className="relative overflow-hidden rounded-3xl px-8 py-14 text-center sm:px-12"
            style={{ background: 'linear-gradient(135deg, #222831 0%, #2f4a4d 55%, #76ABAE 140%)' }}
          >
            <h2 className="font-display text-3xl font-bold text-white sm:text-4xl">
              Try the platform yourself
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-sm leading-relaxed text-white/70">
              Create a demo student profile in under a minute. No email needed, and every tool is
              open to you right after signing up.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
              <button
                type="button"
                onClick={() => navigate(primaryCta.to)}
                className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-semibold text-light-accent transition-transform hover:-translate-y-0.5 sm:w-auto"
              >
                {primaryCta.label}
                <ArrowRight className="h-4 w-4" />
              </button>
              {!isAuthenticated && (
                <Link
                  to="/login"
                  className="inline-flex w-full items-center justify-center rounded-xl border border-white/25 px-6 py-3.5 text-sm font-semibold text-white transition-colors hover:bg-white/10 sm:w-auto"
                >
                  I already have an account
                </Link>
              )}
            </div>
          </div>
        </Reveal>
      </Section>

      {/* ---------- Footer ---------- */}
      <footer id="about" className="scroll-mt-20 border-t border-border bg-surface">
        <Section className="py-12">
          <div className="grid gap-10 md:grid-cols-[1.2fr_1fr_1fr]">
            <div>
              <div className="flex items-center gap-2.5">
                <span className="flex h-8 w-8 items-center justify-center rounded-lg" style={{ background: '#76ABAE' }}>
                  <Brain className="h-4 w-4 text-white" />
                </span>
                <span className="font-display text-sm font-bold">EduFusion AI</span>
              </div>
              <p className="mt-4 max-w-sm text-sm leading-relaxed text-light-accent/55">
                A suite of AI tools for digital education. Graduation project, Computer Engineering
                Department, Faculty of Engineering, Islamic University of Gaza.
              </p>
            </div>

            <div>
              <p className="font-mono text-xs uppercase tracking-widest text-light-accent/40">Team</p>
              <ul className="mt-4 space-y-2 text-sm text-light-accent/60">
                {TEAM.map((name) => <li key={name}>{name}</li>)}
              </ul>
            </div>

            <div>
              <p className="font-mono text-xs uppercase tracking-widest text-light-accent/40">Supervisor</p>
              <p className="mt-4 text-sm text-light-accent/60">Prof. Wesam Ashour</p>

              <p className="mt-6 font-mono text-xs uppercase tracking-widest text-light-accent/40">Platform</p>
              <div className="mt-4 flex flex-col gap-2 text-sm text-light-accent/60">
                <Link to="/login" className="hover:text-light-accent">Sign in</Link>
                <Link to="/register" className="hover:text-light-accent">Create an account</Link>
              </div>
            </div>
          </div>

          <div className="mt-10 border-t border-border pt-6 text-xs text-light-accent/40">
            Gaza, Palestine · 2026 — EduFusion AI. Prototype built for academic demonstration.
          </div>
        </Section>
      </footer>
    </div>
  );
}
